### ISSUE TITLE
Setup IPMI serial console

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-dell#2]
To set up the ipmi serial console, one needs to set (at least?) the following variables via racadm or some equivalent mechanism:

<pre><code>
IPMI_USERNAME=$USRNAME IPMI_PASSWORD=$PASSWD racadm.sh pe4-ipmi set iDRAC.IPMILan.1.Enable Enabled
IPMI_USERNAME=$USRNAME IPMI_PASSWORD=$PASSWD racadm.sh pe4-ipmi set iDRAC.Users.3.IpmiLanPrivilege Administrator
IPMI_USERNAME=$USRNAME IPMI_PASSWORD=$PASSWD racadm.sh pe4-ipmi set iDRAC.Users.3.IpmiSerialPrivilege Administrator
IPMI_USERNAME=$USRNAME IPMI_PASSWORD=$PASSWD racadm.sh pe4-ipmi set iDRAC.Users.3.SolEnable Enable
</code></pre>

where "Users.3" is the IPMI admin users for which one wants to enabled remote IPMI access.

Then, in /etc/default/grub on the node one needs to modify the lines with the following keys as:

<pre><code>
GRUB_TERMINAL_OUTPUT="console serial"
GRUB_CMDLINE_LINUX="selinux=0 crashkernel=auto rd.lvm.lv=centos_pe4/root rd.lvm.lv=centos_pe4/swap console=tty0 console=ttyS0,115200n8"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
</code></pre>

That is, for the GRUB_TERMINAL_OUTPUT one needs to add "serial", for the GRUB_CMDLINE_LINUX one should remove "rhgb quiet" and add "console=ttyS0,115200n8". And finally add the GRUB_SERIAL_COMMAND line.

After this, one needs to run

<pre><code>
grub2-mkconfig > /boot/grub2/grub.cfg
</code></pre>

and reboot.

The above is how to do it manually; it would be nice if this could be made automatically via ansible and/or when the node is kickstarted.

**Comment by martbhell** [comment]
We have this https://github.com/CSC-IT-Center-for-Science/ansible-role-serial-console
It's not added or tested on the fgci nodes yet though.
Do you think the above role would work? Then we can just add it to all the playbooks (it should only make grub2 changes if vendor is "HP" or "Dell Inc.")

We haven't ansibilized any IPMI/iDRAC changes yet.

**Comment by jabl** [comment]
Ooh, I wasn't aware of that. Seems to do most of what I'm asking. Based on a quick look at redhat.yml there seems to be some minor(?) differences compared to the above (which is roughly what we have in the FGI/SL6 cluster):
- GRUB_TERMINAL should(?) probably be "console serial" so that you can get the grub prompt both over IPMI SOL and a "real" console.
- The first block with "rhgb quiet" blows away the line with GRUB_CMDLINE_LINUX, then only the GRUB_CMDLINE_LINUX_DEFAULT is added back with a later block. So does the recovery mode boot stanza work at all then?
- Also, the block with GRUB_CMDLINE_LINUX_DEFAULT apparently blows away all this stuff about on which LV's the root fs and swap partition etc. reside. Does the thing boot properly without those? Again, a slightly fancier regex could only add the serial console stuff without removing whatever is there before.
- Only changes to the GRUB_CMDLINE_LINUX_DEFAULT block trigger regeneration of grub.cfg. Also, it generates the grub.cfg in a place which apparently is for EFI; on FGCI clusters EFI is disabled(?) and we use the legacy bios, so in that case the path ought to be /boot/grub2/grub.cfg.

**Comment by martbhell** [comment]
All good points. So we haven't tested this on an FGCI node. Sounds like there's quite a few improvements needed to make it work there.

**Comment by martbhell** [comment]
Some progress and updates in a branch in the serial-console repo.
- There are several GRUB_TERMINAL_ settings. All of them gets overridden by GRUB_TERMINAL=
- The intention with the rhgb quiet$ is to only remove if it's at the end of a line. If it's in the middle or not at all it should not affect any lines. I'll have to test the recovery boot options.
- For EFI/Legacy. Checking if a directory exists under /sys and then update different files.

https://github.com/CSC-IT-Center-for-Science/ansible-role-serial-console/commits/BIOS_Support

**Comment by martbhell** [comment]
I merged my changes into the ansible-role-serial-console git.
After applying this role to one of the io test nodes /boot/grub2/grub.cfg the changes to /boot/grub2/grub.cfg are like below:

https://gist.github.com/martbhell/1cd9437e70df352c977c

It removes the LANG= setting. But anyway on another of our test nodes the $LANG variable in output of 'env` is en_US.UTF-8 even if LANG=en_GB.UTF-8 in the grub2.

The rescue console works.

No variables in /etc/default/grub were overwritten.

Have not actually tested the IPMI console yet. Might be a network firewall in the way.

**Comment by martbhell** [comment]
Tested on io2 and I can now "sol activate".
@jabl are you happy with the settings we make - and shall I add it to the local.yml and compute.yml playbooks?

**Comment by jabl** [comment]
Well, there's still some weirdness:
- the kernel command line in /boot/grub2/grub.cfg is like:

linux16 /boot/vmlinuz-3.10.0-327.4.5.el7.x86_64 root=UUID=e766e13e-8b79-4f04-8efc-0674e791c44a ro selinux=0 crashkernel=auto rhgb quiet console=tty0 console=tty0 console=ttyS0,115200

That is, the "rhgb quiet" is still there, and "console=tty0" is there twice. That's because the GRUB_CMDLINE_LINUX_DEFAULT is appended to GRUB_CMDLINE_LINUX. So maybe it would be easier to just use GRUB_CMDLINE_LINUX and remove any GRUB_CMDLINE_LINUX_DEFAULT line..
- In /etc/default/grub there is both GRUB_TERMINAL_OUTPUT and GRUB_TERMINAL. According to the grub manual, GRUB_TERMINAL overrides GRUB_TERMINAL_OUTPUT. So per se not an invalid configuration, but maybe a bit confusing.

That being said, it does appear to work, so I suppose it's mostly how pedantic you are.. :)

**Comment by martbhell** [comment]
We should aspire for greatness I suppose :)

**Comment by martbhell** [comment]
For "rhgb quiet" in centos7 there's a plymouth-set-default-theme command.
Maybe we can use that instead of regexps. Needs some testing first.

Basic workflow according to Internet:
- plymouth-set-default-theme # check what it's set to
- plymouth-set-default-theme # change it to details/text
- dracut -f

As for GRUB_TERMINAL_ I'm fine with having multiple. More afraid of breaking grub by removing lines.

**Comment by martbhell** [comment]
When I'm using "ipmitool ... -I lanplus sol activate" I could not spot a difference between with "rhgb quiet", without it and with between "charge" and "text" settings in plymouth-set-default-theme.
Is the "rhgb quiet" causing some issues for you (of course I have not checked the JAVA virtual console).
If not, I'd be fine with us adding the serial-console role to fgci and closing this issue.

**Comment by martbhell** [comment]
This is working now - closing.
